/*
Copyright The Ratify Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package ratify

import (
	"context"

	ocispec "github.com/opencontainers/image-spec/specs-go/v1"
)

// PolicyDecision is the decision made by the policy enforcer.
type PolicyDecision int

const (
	// Undertermined is the initial or a temporary state of the policy decision.
	Undetermined PolicyDecision = iota
	// Deny is the final state when the policy evaluation is failed.
	Deny
	// Allow is the final state when the policy evaluation is succeeded.
	Allow
)

// ValidationReport describes the results of verifying an artifact and its
// nested artifacts by available verifiers.
type ValidationReport struct {
	// Subject is the subject reference of the artifact being verified.
	// Required.
	Subject string

	// Subject is the report of the subject artifact being verified. Required.
	SubjectReport *ValidationReport

	// Results are generated by verifiers while verifying the subject against
	// the referrer artifact. Required.
	// e.g. If the Subject is a container image, Artifact is a descriptor to
	// Notation signature. Results are generated by Notation verifiers verifying
	// the image against the signature.
	Results []*VerificationResult

	// Artifact is the descriptor of the referrer artifact being verified
	// against with. Required.
	Artifact ocispec.Descriptor

	// ArtifactReports is reports of verifying referrer artifacts. Optional.
	// e.g. If the Subject is a container image, Artifact is a descriptor to
	// SBOM which is signed by a Notation signature. ArtifactReports are
	// generated by the executor verifying the SBOM against the signature.
	ArtifactReports []*ValidationReport

	// PolicyEvaluationState is the state saving all required information to
	// evaluate the policy against the report. Optional.
	PolicyEvaluationState EvaluationState
}

// EvaluationState is an interface that is used for policy enforcer to track
// states and make policy decisions.
type EvaluationState interface {
	// CreateNextState creates the next state in terms of the next artifact to be
	// verified. If the policy enforcer allows policy evaluation during
	// verifying, this method MUST be implemented.
	CreateNextState(artifact ocispec.Descriptor) EvaluationState

	// Decision returns the policy decision saved in the state.
	Decision() PolicyDecision
}

// PolicyEnforcer is an interface with methods that make policy decisions.
type PolicyEnforcer interface {
	// EvaluateReport determines the final outcome of validation report
	// generated by the executor verifying the subject artifact and its
	// associated artifacts.
	EvaluateReport(ctx context.Context, report *ValidationReport) (PolicyDecision, error)

	// EvaluateResult determines the outcome of aggregated validation report
	// with a single verification result. This MUST be implemented if
	// AllowEvalDuringVerify returns true.
	EvaluateResult(ctx context.Context, report *ValidationReport, result *VerificationResult) (PolicyDecision, error)

	// RequireFurtherVerification returns false if the verifier could be skipped
	// for the given artifact
	RequireFurtherVerification(ctx context.Context, artifactReport *ValidationReport, verifier Verifier) (bool, error)

	// NewEvaluationState returns a new evaluation state that is used to track
	// the policy evaluation state.
	NewEvaluationState() EvaluationState

	// AllowEvalDuringVerify returns true if the policy enforcer allows policy
	// evaluation during verification so that the executor can skip verifying
	// the artifact if the policy evaluation result is already decided.
	AllowEvalDuringVerify() bool
}
